# Generated by Django 4.0.6 on 2022-07-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-doc_num']},
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_num',
            field=models.IntegerField(unique=True),
        ),
    ]
