# Generated by Django 4.0.6 on 2022-07-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_options_alter_document_doc_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000, unique=True)),
                ('doc_num', models.IntegerField(unique=True)),
                ('language', models.CharField(max_length=15)),
                ('raw_text', models.TextField()),
            ],
            options={
                'ordering': ['-doc_num'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('number', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='documents.suspiciousdocument')),
            ],
            options={
                'ordering': ['document', 'number'],
            },
        ),
    ]
