# Generated by Django 4.0.6 on 2022-07-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_suspiciousdocument_suspicioussentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='preprocessed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
