# Generated by Django 4.0.6 on 2022-07-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_sentence_preprocessed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspicioussentence',
            name='preprocessed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
