# Generated by Django 4.0.6 on 2022-07-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_suspicioussentence_preprocessed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='fasttext_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspicioussentence',
            name='fasttext_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
