# Generated by Django 4.0.6 on 2022-07-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_sentence_fasttext_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='number',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='suspicioussentence',
            name='number',
            field=models.IntegerField(db_index=True),
        ),
    ]
