# Generated by Django 4.0.6 on 2022-08-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_remove_sentence_fasttext_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspicioussentence',
            name='fasttext_vector',
        ),
    ]
