# Generated by Django 4.1 on 2022-08-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_remove_document_type_document_authors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="keywords",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suspiciousdocument",
            name="keywords",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
