# Generated by Django 4.1 on 2022-08-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_givenplagiarismcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="givenplagiarismcase",
            name="type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
