# Generated by Django 4.1 on 2022-08-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_plagiarismcase"),
    ]

    operations = [
        migrations.AddField(
            model_name="plagiarismcase",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
