# Generated by Django 4.1 on 2022-08-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_alter_document_doc_num_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="plagiarism_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="suspiciousdocument",
            name="plagiarism_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
